.PHONY: help install build clean test test-pg proto proto-gateway proto-protoc run-server run-cli dev install-service uninstall-service service-status service-logs db-up db-down migrate migrate-data tls-cert docker-build deploy

# Variables
BINARY_NAME_CLI=todo
BINARY_NAME_SERVER=server
GOBIN=$(shell go env GOPATH)/bin
PROTO_DIR=proto
DATA_DIR=$(HOME)/.config/todolist
MIGRATIONS_DIR=migrations
# Local Postgres for Phase 1 (TODO_STORAGE=postgres). Override as needed.
PG_URL?=postgres://todo:todo@localhost:5432/todo?sslmode=disable
# Local self-signed TLS material for Phase 4 de-risking. Override as needed.
CERT_DIR?=certs
TLS_HOST?=localhost
# Server container image tag for Phase 6 hosting. Override as needed.
IMAGE?=todolist-server:dev

help: ## Show this help message
	@echo "Usage: make [target]"
	@echo ""
	@echo "Available targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-15s %s\n", $$1, $$2}'

install: build ## Install binaries to $(GOBIN)
	@echo "Installing binaries to $(GOBIN)..."
	go install ./cmd/todo
	go install ./cmd/server
	@echo "✅ Installation complete!"
	@echo "   - todo: $(GOBIN)/$(BINARY_NAME_CLI)"
	@echo "   - server: $(GOBIN)/$(BINARY_NAME_SERVER)"

build: ## Build binaries (without installing)
	@echo "Building binaries..."
	go build -o $(BINARY_NAME_CLI) ./cmd/todo
	go build -o $(BINARY_NAME_SERVER) ./cmd/server
	@echo "✅ Build complete!"

clean: ## Remove built binaries
	@echo "Cleaning up..."
	rm -f $(BINARY_NAME_CLI) $(BINARY_NAME_SERVER)
	@echo "✅ Clean complete!"

test: ## Run all tests
	@echo "Running tests..."
	go test -v ./...
	@echo "✅ Tests complete!"

test-pg: ## Run tests against a local Postgres (requires `make db-up && make migrate`)
	@echo "Running tests with Postgres backend..."
	TODO_TEST_DATABASE_URL="$(PG_URL)" go test -v ./libs/storage/...
	@echo "✅ Postgres tests complete!"

db-up: ## Start a local Postgres for development/tests (Docker)
	@echo "Starting local Postgres..."
	docker compose up -d postgres
	@echo "✅ Postgres up (URL: $(PG_URL))"

db-down: ## Stop and remove the local Postgres
	@echo "Stopping local Postgres..."
	docker compose down
	@echo "✅ Postgres down!"

migrate: ## Apply SQL migrations to $(PG_URL) (requires psql)
	@echo "Applying migrations to $(PG_URL)..."
	@for f in $(MIGRATIONS_DIR)/*.sql; do \
		echo "  -> $$f"; \
		psql "$(PG_URL)" -v ON_ERROR_STOP=1 -f "$$f"; \
	done
	@echo "✅ Migrations applied!"

migrate-data: ## Migrate local data.json into Postgres for the logged-in user (Phase 5; needs `todo login` + DATABASE_URL). Use ARGS="--dry-run" to preview.
	@echo "Migrating ~/.config/todolist/data.json into Postgres (idempotent, data.json kept as .bak)..."
	@go run ./cmd/todo migrate $(ARGS)

tls-cert: ## Generate a local self-signed TLS cert/key for Phase 4 de-risking (requires openssl)
	@echo "Generating self-signed certificate for $(TLS_HOST) in $(CERT_DIR)/..."
	@mkdir -p $(CERT_DIR)
	openssl req -x509 -newkey rsa:2048 -nodes \
		-keyout $(CERT_DIR)/server.key -out $(CERT_DIR)/server.crt \
		-days 365 -subj "/CN=$(TLS_HOST)" \
		-addext "subjectAltName=DNS:$(TLS_HOST)"
	@echo "✅ Cert generated. Run server with:"
	@echo "    TLS_CERT_FILE=$(CERT_DIR)/server.crt TLS_KEY_FILE=$(CERT_DIR)/server.key make run-server"
	@echo "   and the CLI with:"
	@echo "    TODO_TLS_CA_FILE=$(CERT_DIR)/server.crt TODO_TLS_SERVER_NAME=$(TLS_HOST) make run-cli ARGS=\"list\""

docker-build: ## Build the server container image (Phase 6)
	@echo "Building server image $(IMAGE)..."
	docker build -t $(IMAGE) .

deploy: ## Deploy the server to Fly.io (Phase 6; requires flyctl + secrets set, see docs/deployment.md)
	@echo "Deploying to Fly.io (ensure 'fly secrets set DATABASE_URL=...' was run)..."
	fly deploy

proto: ## Generate protobuf Go/gRPC stubs via buf (resolves google/api deps)
	@echo "Generating protobuf Go/gRPC stubs (buf)..."
	buf dep update
	buf generate
	@echo "✅ Protobuf generation complete!"

proto-gateway: proto ## Generate Go/gRPC stubs + REST gateway stub (.gw.pb.go) via buf (Phase 7 volet B)
	@echo "✅ Gateway stub generated by 'buf generate' (see buf.gen.yaml)."
	@echo "   Reminder: regenerating adds dep github.com/grpc-ecosystem/grpc-gateway/v2 -> run 'go mod tidy'."

proto-protoc: ## (Legacy, NON FONCTIONNEL tant que les annotations google.api.http sont présentes -> utiliser 'make proto' via buf ; voir docs/grpc-gateway.md §4)
	@echo "WARNING: plain protoc échoue sur import google/api/annotations.proto (non vendoré)."
	@echo "         Utiliser 'make proto' (buf). Voir docs/grpc-gateway.md §4."
	@echo "Generating protobuf files (plain protoc, no gateway/annotations)..."
	protoc --go_out=. --go_opt=paths=source_relative \
		--go-grpc_out=. --go-grpc_opt=paths=source_relative \
		$(PROTO_DIR)/todoList.proto
	@echo "✅ Protobuf generation complete (go/go-grpc only)!"

run-server: ## Run the server (foreground)
	@echo "Starting server..."
	@go run ./cmd/server

run-cli: ## Run the CLI (usage: make run-cli ARGS="list")
	@go run ./cmd/todo $(ARGS)

dev: ## Install and restart server
	@echo "Installing and restarting server..."
	@pkill -f "server" 2>/dev/null || true
	@make install
	@echo "Starting server in background..."
	@$(GOBIN)/server > /tmp/todoserver.log 2>&1 &
	@sleep 1
	@echo "✅ Server restarted!"
	@echo "Test with: todo list"

setup-data: ## Setup data directory and copy initial data
	@echo "Setting up data directory..."
	@mkdir -p $(DATA_DIR)
	@if [ -f data/data.json ]; then \
		cp data/data.json $(DATA_DIR)/; \
		echo "✅ Data file copied to $(DATA_DIR)"; \
	else \
		echo '{"lists":{}}' > $(DATA_DIR)/data.json; \
		echo "✅ Created empty data file at $(DATA_DIR)"; \
	fi

uninstall: ## Uninstall binaries from $(GOBIN)
	@echo "Uninstalling binaries..."
	rm -f $(GOBIN)/$(BINARY_NAME_CLI)
	rm -f $(GOBIN)/$(BINARY_NAME_SERVER)
	@echo "✅ Uninstall complete!"

restart-server: ## Kill and restart the server
	@echo "Restarting server..."
	@pkill -f "server" 2>/dev/null || true
	@sleep 1
	@$(GOBIN)/server > /tmp/todoserver.log 2>&1 &
	@sleep 1
	@echo "✅ Server restarted!"

stop: ## Stop the server
	@echo "Stopping server..."
	@pkill -f "$(GOBIN)/server" 2>/dev/null || true
	@pkill -x "server" 2>/dev/null || true
	@echo "✅ Server stopped!"

logs: ## Show server logs
	@tail -f /tmp/todoserver.log

status: ## Check if server is running
	@if pgrep -f "$(GOBIN)/server" > /dev/null 2>&1; then \
		echo "✅ Server is running (PID: $$(pgrep -f '$(GOBIN)/server'))"; \
	elif pgrep -x "server" > /dev/null 2>&1; then \
		echo "✅ Server is running (PID: $$(pgrep -x 'server'))"; \
	else \
		echo "❌ Server is not running"; \
	fi

fmt: ## Format Go code
	@echo "Formatting code..."
	go fmt ./...
	@echo "✅ Format complete!"

lint: ## Run linter (requires golangci-lint)
	@echo "Running linter..."
	golangci-lint run
	@echo "✅ Lint complete!"

install-service: install ## Install launchd service (user mode, starts on login)
	@echo "Installing launchd service..."
	@./scripts/install-service.sh

uninstall-service: ## Uninstall launchd service
	@echo "Uninstalling launchd service..."
	@./scripts/uninstall-service.sh

service-status: ## Check launchd service status
	@if launchctl list | grep -q "com.todolist.server"; then \
		echo "✅ Service is running"; \
		launchctl list | grep "com.todolist.server"; \
	else \
		echo "❌ Service is not running"; \
	fi

service-logs: ## Show service logs (requires service to be installed)
	@echo "Server logs:"
	@tail -f $(DATA_DIR)/server.log
