// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/todoList.proto

package todo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TodoListService_CreateTodoList_FullMethodName      = "/todo.TodoListService/CreateTodoList"
	TodoListService_GetTodoLists_FullMethodName        = "/todo.TodoListService/GetTodoLists"
	TodoListService_ShowTodoListItems_FullMethodName   = "/todo.TodoListService/ShowTodoListItems"
	TodoListService_DeleteTodoList_FullMethodName      = "/todo.TodoListService/DeleteTodoList"
	TodoListService_DeleteTodoListItems_FullMethodName = "/todo.TodoListService/DeleteTodoListItems"
	TodoListService_UpdateTodoList_FullMethodName      = "/todo.TodoListService/UpdateTodoList"
	TodoListService_UpdateTodoListItem_FullMethodName  = "/todo.TodoListService/UpdateTodoListItem"
)

// TodoListServiceClient is the client API for TodoListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoListServiceClient interface {
	CreateTodoList(ctx context.Context, in *CreateTodoListRequest, opts ...grpc.CallOption) (*CreateTodoListResponse, error)
	GetTodoLists(ctx context.Context, in *GetTodoListsRequest, opts ...grpc.CallOption) (*GetTodoListsResponse, error)
	ShowTodoListItems(ctx context.Context, in *ShowTodoListItemsRequest, opts ...grpc.CallOption) (*ShowTodoListItemsResponse, error)
	DeleteTodoList(ctx context.Context, in *DeleteTodoListRequest, opts ...grpc.CallOption) (*DeleteTodoListResponse, error)
	DeleteTodoListItems(ctx context.Context, in *DeleteTodoListItemsRequest, opts ...grpc.CallOption) (*DeleteTodoListItemsResponse, error)
	UpdateTodoList(ctx context.Context, in *UpdateTodoListRequest, opts ...grpc.CallOption) (*UpdateTodoListResponse, error)
	UpdateTodoListItem(ctx context.Context, in *UpdateTodoListItemRequest, opts ...grpc.CallOption) (*UpdateTodoListItemResponse, error)
}

type todoListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoListServiceClient(cc grpc.ClientConnInterface) TodoListServiceClient {
	return &todoListServiceClient{cc}
}

func (c *todoListServiceClient) CreateTodoList(ctx context.Context, in *CreateTodoListRequest, opts ...grpc.CallOption) (*CreateTodoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTodoListResponse)
	err := c.cc.Invoke(ctx, TodoListService_CreateTodoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoListServiceClient) GetTodoLists(ctx context.Context, in *GetTodoListsRequest, opts ...grpc.CallOption) (*GetTodoListsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTodoListsResponse)
	err := c.cc.Invoke(ctx, TodoListService_GetTodoLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoListServiceClient) ShowTodoListItems(ctx context.Context, in *ShowTodoListItemsRequest, opts ...grpc.CallOption) (*ShowTodoListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShowTodoListItemsResponse)
	err := c.cc.Invoke(ctx, TodoListService_ShowTodoListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoListServiceClient) DeleteTodoList(ctx context.Context, in *DeleteTodoListRequest, opts ...grpc.CallOption) (*DeleteTodoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTodoListResponse)
	err := c.cc.Invoke(ctx, TodoListService_DeleteTodoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoListServiceClient) DeleteTodoListItems(ctx context.Context, in *DeleteTodoListItemsRequest, opts ...grpc.CallOption) (*DeleteTodoListItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTodoListItemsResponse)
	err := c.cc.Invoke(ctx, TodoListService_DeleteTodoListItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoListServiceClient) UpdateTodoList(ctx context.Context, in *UpdateTodoListRequest, opts ...grpc.CallOption) (*UpdateTodoListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTodoListResponse)
	err := c.cc.Invoke(ctx, TodoListService_UpdateTodoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoListServiceClient) UpdateTodoListItem(ctx context.Context, in *UpdateTodoListItemRequest, opts ...grpc.CallOption) (*UpdateTodoListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTodoListItemResponse)
	err := c.cc.Invoke(ctx, TodoListService_UpdateTodoListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoListServiceServer is the server API for TodoListService service.
// All implementations must embed UnimplementedTodoListServiceServer
// for forward compatibility.
type TodoListServiceServer interface {
	CreateTodoList(context.Context, *CreateTodoListRequest) (*CreateTodoListResponse, error)
	GetTodoLists(context.Context, *GetTodoListsRequest) (*GetTodoListsResponse, error)
	ShowTodoListItems(context.Context, *ShowTodoListItemsRequest) (*ShowTodoListItemsResponse, error)
	DeleteTodoList(context.Context, *DeleteTodoListRequest) (*DeleteTodoListResponse, error)
	DeleteTodoListItems(context.Context, *DeleteTodoListItemsRequest) (*DeleteTodoListItemsResponse, error)
	UpdateTodoList(context.Context, *UpdateTodoListRequest) (*UpdateTodoListResponse, error)
	UpdateTodoListItem(context.Context, *UpdateTodoListItemRequest) (*UpdateTodoListItemResponse, error)
	mustEmbedUnimplementedTodoListServiceServer()
}

// UnimplementedTodoListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTodoListServiceServer struct{}

func (UnimplementedTodoListServiceServer) CreateTodoList(context.Context, *CreateTodoListRequest) (*CreateTodoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTodoList not implemented")
}
func (UnimplementedTodoListServiceServer) GetTodoLists(context.Context, *GetTodoListsRequest) (*GetTodoListsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodoLists not implemented")
}
func (UnimplementedTodoListServiceServer) ShowTodoListItems(context.Context, *ShowTodoListItemsRequest) (*ShowTodoListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowTodoListItems not implemented")
}
func (UnimplementedTodoListServiceServer) DeleteTodoList(context.Context, *DeleteTodoListRequest) (*DeleteTodoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTodoList not implemented")
}
func (UnimplementedTodoListServiceServer) DeleteTodoListItems(context.Context, *DeleteTodoListItemsRequest) (*DeleteTodoListItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTodoListItems not implemented")
}
func (UnimplementedTodoListServiceServer) UpdateTodoList(context.Context, *UpdateTodoListRequest) (*UpdateTodoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTodoList not implemented")
}
func (UnimplementedTodoListServiceServer) UpdateTodoListItem(context.Context, *UpdateTodoListItemRequest) (*UpdateTodoListItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTodoListItem not implemented")
}
func (UnimplementedTodoListServiceServer) mustEmbedUnimplementedTodoListServiceServer() {}
func (UnimplementedTodoListServiceServer) testEmbeddedByValue()                         {}

// UnsafeTodoListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoListServiceServer will
// result in compilation errors.
type UnsafeTodoListServiceServer interface {
	mustEmbedUnimplementedTodoListServiceServer()
}

func RegisterTodoListServiceServer(s grpc.ServiceRegistrar, srv TodoListServiceServer) {
	// If the following call pancis, it indicates UnimplementedTodoListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TodoListService_ServiceDesc, srv)
}

func _TodoListService_CreateTodoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).CreateTodoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoListService_CreateTodoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).CreateTodoList(ctx, req.(*CreateTodoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoListService_GetTodoLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodoListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).GetTodoLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoListService_GetTodoLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).GetTodoLists(ctx, req.(*GetTodoListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoListService_ShowTodoListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowTodoListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).ShowTodoListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoListService_ShowTodoListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).ShowTodoListItems(ctx, req.(*ShowTodoListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoListService_DeleteTodoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).DeleteTodoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoListService_DeleteTodoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).DeleteTodoList(ctx, req.(*DeleteTodoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoListService_DeleteTodoListItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoListItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).DeleteTodoListItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoListService_DeleteTodoListItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).DeleteTodoListItems(ctx, req.(*DeleteTodoListItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoListService_UpdateTodoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).UpdateTodoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoListService_UpdateTodoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).UpdateTodoList(ctx, req.(*UpdateTodoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoListService_UpdateTodoListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTodoListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoListServiceServer).UpdateTodoListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoListService_UpdateTodoListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoListServiceServer).UpdateTodoListItem(ctx, req.(*UpdateTodoListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoListService_ServiceDesc is the grpc.ServiceDesc for TodoListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo.TodoListService",
	HandlerType: (*TodoListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodoList",
			Handler:    _TodoListService_CreateTodoList_Handler,
		},
		{
			MethodName: "GetTodoLists",
			Handler:    _TodoListService_GetTodoLists_Handler,
		},
		{
			MethodName: "ShowTodoListItems",
			Handler:    _TodoListService_ShowTodoListItems_Handler,
		},
		{
			MethodName: "DeleteTodoList",
			Handler:    _TodoListService_DeleteTodoList_Handler,
		},
		{
			MethodName: "DeleteTodoListItems",
			Handler:    _TodoListService_DeleteTodoListItems_Handler,
		},
		{
			MethodName: "UpdateTodoList",
			Handler:    _TodoListService_UpdateTodoList_Handler,
		},
		{
			MethodName: "UpdateTodoListItem",
			Handler:    _TodoListService_UpdateTodoListItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/todoList.proto",
}
