// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: todoList.proto

package todo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTodoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Tasks         []string               `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoListRequest) Reset() {
	*x = CreateTodoListRequest{}
	mi := &file_todoList_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoListRequest) ProtoMessage() {}

func (x *CreateTodoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todoList_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoListRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoListRequest) Descriptor() ([]byte, []int) {
	return file_todoList_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTodoListRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTodoListRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTodoListRequest) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateTodoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoListResponse) Reset() {
	*x = CreateTodoListResponse{}
	mi := &file_todoList_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoListResponse) ProtoMessage() {}

func (x *CreateTodoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todoList_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoListResponse.ProtoReflect.Descriptor instead.
func (*CreateTodoListResponse) Descriptor() ([]byte, []int) {
	return file_todoList_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTodoListResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTodoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoListRequest) Reset() {
	*x = GetTodoListRequest{}
	mi := &file_todoList_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoListRequest) ProtoMessage() {}

func (x *GetTodoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todoList_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoListRequest.ProtoReflect.Descriptor instead.
func (*GetTodoListRequest) Descriptor() ([]byte, []int) {
	return file_todoList_proto_rawDescGZIP(), []int{2}
}

func (x *GetTodoListRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTodoListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tasks         []string               `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoListResponse) Reset() {
	*x = GetTodoListResponse{}
	mi := &file_todoList_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoListResponse) ProtoMessage() {}

func (x *GetTodoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todoList_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoListResponse.ProtoReflect.Descriptor instead.
func (*GetTodoListResponse) Descriptor() ([]byte, []int) {
	return file_todoList_proto_rawDescGZIP(), []int{3}
}

func (x *GetTodoListResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTodoListResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTodoListResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTodoListResponse) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

var File_todoList_proto protoreflect.FileDescriptor

const file_todoList_proto_rawDesc = "" +
	"\n" +
	"\x0etodoList.proto\x12\x04todo\"e\n" +
	"\x15CreateTodoListRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05tasks\x18\x03 \x03(\tR\x05tasks\"(\n" +
	"\x16CreateTodoListResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12GetTodoListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"s\n" +
	"\x13GetTodoListResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05tasks\x18\x04 \x03(\tR\x05tasks2\xa6\x01\n" +
	"\x0fTodoListService\x12M\n" +
	"\x0eCreateTodoList\x12\x1b.todo.CreateTodoListRequest\x1a\x1c.todo.CreateTodoListResponse\"\x00\x12D\n" +
	"\vGetTodoList\x12\x18.todo.GetTodoListRequest\x1a\x19.todo.GetTodoListResponse\"\x00B,Z*github.com/oceane-vlt/todolist/proto/;todob\x06proto3"

var (
	file_todoList_proto_rawDescOnce sync.Once
	file_todoList_proto_rawDescData []byte
)

func file_todoList_proto_rawDescGZIP() []byte {
	file_todoList_proto_rawDescOnce.Do(func() {
		file_todoList_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todoList_proto_rawDesc), len(file_todoList_proto_rawDesc)))
	})
	return file_todoList_proto_rawDescData
}

var file_todoList_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_todoList_proto_goTypes = []any{
	(*CreateTodoListRequest)(nil),  // 0: todo.CreateTodoListRequest
	(*CreateTodoListResponse)(nil), // 1: todo.CreateTodoListResponse
	(*GetTodoListRequest)(nil),     // 2: todo.GetTodoListRequest
	(*GetTodoListResponse)(nil),    // 3: todo.GetTodoListResponse
}
var file_todoList_proto_depIdxs = []int32{
	0, // 0: todo.TodoListService.CreateTodoList:input_type -> todo.CreateTodoListRequest
	2, // 1: todo.TodoListService.GetTodoList:input_type -> todo.GetTodoListRequest
	1, // 2: todo.TodoListService.CreateTodoList:output_type -> todo.CreateTodoListResponse
	3, // 3: todo.TodoListService.GetTodoList:output_type -> todo.GetTodoListResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_todoList_proto_init() }
func file_todoList_proto_init() {
	if File_todoList_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todoList_proto_rawDesc), len(file_todoList_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todoList_proto_goTypes,
		DependencyIndexes: file_todoList_proto_depIdxs,
		MessageInfos:      file_todoList_proto_msgTypes,
	}.Build()
	File_todoList_proto = out.File
	file_todoList_proto_goTypes = nil
	file_todoList_proto_depIdxs = nil
}
